sudo: required
dist: trusty
language: node_js
node_js:
- '9.0'
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - export CI=false
  - export REPO=woa-api
  - export IMAGE_TAG:latest
  - export BUILD_TAG=$REPO:$IMAGE_TAG
  - secure: Lav6GWq9I6B/NZP5O30ees47cqeIKXZCVoHqhgCoxOVoJqFB2ZzeTO8xHbU2rd1etMgyDOEV+wJzriPgjgONyhDgMAHnNYgqjtSVcbdmvl86Gl5pGeyfbkcAzuigoaL6mmUF2tHmHsxxtQwMZkuYB6JMQE1XBpy9wpjZIZpdDB29FCqdnxE8rv2UJsEwJsGIw/iLCcexYgoAkk4BXpNTYOvKRBysDG5mbZmHR83wcBPBI6bHP3OqpiWWXdpTR/ddsDkGhIR6FbaxPbIvb/5gPUwci2fHhH5S4bM3OidMSqX4Y2zirrGlUXSBrwZWZEU7MAL/O47Evr/d5GU+2MUhYh//HVO5qSeaR+aeuhn1+Bl9ybVNnsRzE2RaaeX3sShODgrQggTFPsHxiKHTPDdJ3pg6+tDqTa0eNeOmvCm4y1bmrYM5Rc6wkAyDXkd1ICAH1AcwFNXXDOXjNZyZiXxwBPft54z6pffCAoR9rCtG6XAPYYlslQ7EbwjYyFusUkDKEm0oelX5JH8EM7yEJAf4ezUZlbZN2mb3J4CGZ8AulG0xGjzp3y+8WS0PNUOzNZNlyYqdGUeGivVIUq5B131DjiSQlz9ZhHGnYEDvS71FdVxaQ96aybsIrC7PDzl3+jwBxo7zt6MzWqv00SbyLmtbCVITEWajSOprnkm7SSMuCW4=
  - secure: T6EmlGf1aBdKab6uJijb98e80maBm6W6Ej/i5t+TnlLEDAWFmASwNWRcYWr8NUJ7UxsSxwsDIQXV1GjkQ+XTr9bRg7hWN56ItkqJ5Jjf+d66Xydo3ni+ttpF8om6KJPaz7mDrwL+H1wPjPF63oG8WpNkwXvK9YoSqBSFYyKYCfj5vO6kW0li71rc6a+lMa3tJsgenHewS66hfNPOhgYGChtiMPQYx1thNv39nloHNdnNnXoJ/dTNogEoSMckg7/YCg7cimuLY4VhkO75bhum1eme3SPYF95i2+jOBxNDhjwfneRb6zuzMyqU8X9bYtg9iNM09EDl9cAZl9qiuCrFwhBzx7RoFibBZSwdwHOOxMbXeRZGijo4tTTge/qXGp46NAnHhQZeuLlEEwGtOn8F84nEqjcEn0NcBY3NuZbZvA7ywIuaxsX2/O5Y0hhZfPBykzd4mq43zY/6SmM/x9I19wYMx9/yWxRl+3S3snpy1SnXUcgHZKCUmsrW+lN+kohO3oAtyilYumkddIDmF556WrQVZDLI2jMpZ6m/SXarT3MZzB0EF2FHVRyLh76y4nXLSEFV9A/o3nJxNrHjOPigYMbpgReBu879gSBuxgjDDYqEvnxqmk3ZC0oQOpgkTe71JCqM4/4Huuv63qaiHgacTM25QEKykWSNBSfIa4omXdw=
  - secure: GFuVgGmC9FV1x9FBLR2ovNV1t9NUl9thVNpr9U2dMyXhRCtv9eYuoqR5vESd71ttS4hVYgztcoDto4DT2bTe2Rdel0o5TmQ0NC7WAVrPAoHOZirbsHENXIjeqn00hw4zFBpclpWS2w0UpsEumahiHP+rnPgaCn7j1Vozy4V15oTVMqD00VUBw3hwbyKEV5kkLwHVhdZwMxKegoBJ3hBlhyWEdTo2Sd+X4Hk4q9Gmgzv425E0fh+oDsxFnt+Qz6LekAwipVp7nC1h5g8sqY2amAJWpQA2TcPE/0PndNHTXsEPW7XU6ZmYPzPFU7vlWUQp0lPzxnMfS6wbRnp4jkz61AgAUey6q8Gy/FH02dkjw5hwQajGz2s/XIRMFJwIbnX+jHTNlxDRxDbmknu6E/FbMqGyCtNqvcNcC2yHMOB956a/kGP1w5Ums6VMrThH4E8gc0sGJ87DO751qpUwhS3sdoWkig9okgGl30vSGc4MzZnYw8CXv4olSUF56HfSE7iGw+kbldaGKxNL80/P934znHfgAgvhAWgXlSz6zdrmAp8EN/Cz+RD0Cyk8TFcduoKiuBi4b52cE3CpqdcOcr5kv69dqhHv/sijhP9HEtmgH6L4SkVgUyPQzzrjxbWjxPK0qi3QKEmEexBc6Nl0mNijTc7aP6ydqOewTjurD1jjqGE=

  - secure: L/P237tccsocsBZyL5BnY5KirBmRSHHE6I1g1iRM2TfL7dA7wsRcXX9UfbF8lNqlcGN2SLwVa5yDbZ+cMS5dlRCo9kUmhNd6fTwwRY4BT+Q7HP6GHFBZhoGI2UQQ+774jRjyrhQW37Vo6bDXan9sXqS/YAZiGOKpfEUOszb5vPmkK01Psjx0YsZ3O4bW3iS3TmbMnWggm8RpG5vKt/G4FGZc7SsC2BdSVs7uG6e7kPR97/teflv7N9y56etiUVWGta5YjJz2gTm+wkwQ7VgkcEVhH1lsaoCcHwVQG/glEqMAc4QIC7Ec+VRGAulZvhawD+nLowlonlIlIN4PUNDuzZ0DvGMSYQr5BWJGi65lV/4BTGAUe5LfQSrMNYPF4cZ1QYJMsUCSDfw9dA0Er1zYjbEyY/yOz5PPywVqDNsFb0tdWi1xu9yQrmuPadLJHqAvlnWlBV1e2lJnK0gSdQtNQd2FACpsTYgLW7qt+tQSJZaG3UZA20wzPHdyh1sxtW+HYCkneFrvXGRzA65GdyVRRwYeRHOInKhLgbwKA2wT+C398GZZIUveDMpURtq0dx4cVfkjsGRVZsISIvAhreuQnt8IFya9my5yPiLIzdwzXQyVll1qpM0rlEWCHSIAETNHIH+sauY7O9MUXkXUvRJTBfsX/57efjIC1spSoOlvU5c=
  - secure: s9Pff7bZ0tnyvfFDbfyP47st+3f96gLeIkHJnlNG9mmXZN1+7Jm0ByTaVbFnWcMJFDE0DnHVbvPdm8LKFTjCj8uSy4pzBTc82QlTjk05yqnMmZpTliZCbKuAX473IP5gB3jbGAlILt2VrOMZU4mAGlobf9bNO/lA0ZlgJe9RMrCAnLyd1+Gns3NTalfK72XGiBH5hsM/qqBSCv42x167kdp5M9YlL/a+ddZLUwVNvLD0qZnblIbPFkUcYHouDugbGXfAsa+6FvPIe1dAg9XCleAN1YakFjobMQG6rctqI6VjoabkqbLmGoF6PIaB7pv2T7U6f1rGQmYGN9+vm1u25fn3MBO7TTXmTViQHrIxUFHSdXU3QQO9b9Fy9yGmZJ9KD4Od0Uj/4oPg2ip6ceyaOx59Rervin/nC3cRS+P5H0oP4mSQFOMdD3rCS6VpkLSYGdcnfXw9sIL/Q3nxxIAEGS0YaNn+CNGquLyKX3S6PMx6r2Bnn4uOW98b4x5Aq2FNCM2q35i66SSycRtxANocvjFK3JvKAPkRvCiiZa90O0uR7BQgvzAuF++gi6SVb1hWeXRGPdfDcFr/fAdpUPILYBGIgVBRGpEx86Q2ach5d3vud1A27DZlZr32GECK94zJ4jM19uJ4t7XQQMphnonTUcigMOfJp+ryceIMOcBlfYU=


before_install:
  - echo "TRAVIS_TAG = ${TRAVIS_TAG} - TRAVIS_BRANCH = ${TRAVIS_BRANCH}"
  - echo "$HEROKU_AUTHTOKEN" | docker login --username=$HEROKU_USERNAME --password-stdin registry.heroku.com
  - echo "$GITLAB_PWD" | docker login --username=$GITLAB_USERNAME= --password-stdin registry.gitlab.com
install:
  - echo "skip install"
before_script:
  - echo "skip before_script"
script:
  - docker build -f Dockerfile -t $BUILD_TAG .
  - docker tag $BUILD_TAG registry.heroku.com/$REPO/web
  - docker tag $BUILD_TAG registry.gitlab.com/crixo/$REPO:$IMAGE_TAG
deploy:
  provider: script
  script: bash ./heroku-container-release.sh
  on:
    branch: master

