sudo: required
dist: trusty
language: node_js
node_js:
- '9.0'
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - export CI=false
  - export REPO=woa-api
  - export IMAGE_TAG:latest
  - export BUILD_TAG=$REPO:$IMAGE_TAG
  - secure: o7bfqSVYP9lu0aNJ5yoTE4JMl+y8xbnrSo29IEnKFhYMxj9jA4Y0XSXKdF/PDysuJtBYtvtJbbkTo0OqLvMPn+mIJ+J1Vv391kGGj1GRFThT3o11XrR0X6gkHxf8ckxhA8jLhwQmtsEq7kf/5FnZ5Zfk7Fv0PUwMnvtJ/awGKcrcXLXeHCoNYbn2o05C2W0W2OC2fcKnBoWhWbIxJ+VUXJFvFSxKXa81wiNnhqS9h2JehSxvWlcPnT5hqvjuQBbVqPjNAegy8ERECEX1k/PWKmLPA0DpUKqgjzM15tALkKhMeS5tolalVVczn0xuP7LlbpCsvjoGGaLxtSgqz6fubA59XU5vMywxJAefS5UjikdoaIf2TF2Br+ERNroe8MxADrYWEanZ93O4bFKABOtQ/rY7z1+xcdW6bLm6RM94PnNnPImQKXoHXAAHaynfvMM4OVzj4pMGEo6xnedx3ChYr/cXQMHONV54l3REYHaQkxnLafsZk87nlBvp8bIPwLqYyDZeeWN6dyrhABfFjQBmUoTqHc+KueNEdmAypgQcrGCP0hEI/hvlY7kJeojh1ofvu5L1UFyHKi3K8lGYxrYdHehMPqgA29PfSB0FchDyOzQN0b4kzgYuvYd3dFFEVu2gbf8abOaNNBXJhLyEtfPiY0vD6J5KLYWEYpJseYQ/lIc=
  - secure: NbfzNgUPLHznZz2RWd/wcB4TGOTQ7sXQ54BPhCekzlzCJpQRGvFgyvcwpOIdc8pfBQAo6deTmRR3D2m/4cDUYQxVuALwAkYl92QbTflZXhhihlYvTcyHtxmAMU6PjWCw82pt7k3aEob7QPrkxln8g9Fa1LWgJDUhRXJ789yx4LQ/oUGOCu94F0jmzT66GqE6gQd+diFfWnHt0b4VjqZSczl7VllO32bMPbVzBsJIaYUJfvxz+1m54MuBGZNpGoLIbYr9mxQ2mVIx8r56LQoegnDx16oCxQT/8IyWo15rcQWwoQKIBVuoJz9fpiJLbNvLFE9PEzX+VpUiPFy0JUUVaLtEJ64I3obwOnE+s+KBk4khjdsHYJ6YGP4L2Xptf+2/naL1bfi/jajBuldUkiRGY8ExzE3C1GOiWFkyBzc38DbPMhRn8mlFkbTIqpHjoEscI7FZneYvgSJicrqPTMUwmqJmAw81prVlEdqn/jkoB6RUBYQD2dIFMiZHaMBXqW+nbEDKFHrJU5YSKrQjasWWoQfP/qEhuM6U7HS6GyCLMlzU/7NYPigxo5izHNV95SRkXwMdniRT78hZXawEKAq2IdNl+ePa9k3eYp1dqlX3ClM4UMU3t+WaK2eA2IY/CX2F1dNd1HpLiaHWuVtBcF42r2CmAPmNXNHhKkDidqz2mm8=
  - secure: BdEbt4+3hZLNYLyb7rF1pQb6rtvMPNBbA+7f8YiF1vlzlufoKBNgIoHNsD3qBkA2TZ0Pik/kn1k++WbJRXN92Xa0jnScCbOruOK2xn50mSlj3k+kycq9w54FlUc8PuNlLhc5uEHO7YAVOFBvzrrKFFUUg8s/tLJfKfuNvI8XStT8W8r94I+/7K2kh7aZikn3hqAA+SRb5kLCS20J0WtGxEpT1KKa97SewB7lFfj2bNF7V27znkto8VbJxbwEU9IExm6PM2nEjlDO4tf5iz+Fhy58RTJkKZCDfUV/B3Z4S3ka/JpMB9fGhOGvmUDRS7klSnjGLpcAgLAs0DA9ud8STCUCazlTbbqQkxTQWQYa+U/FUoEMka4I5dAgYSUneC2eg0Cs3D1eiG3wJ+yQiZPo5PzS4TmlyzpXeyYx9/OVschtYZlVFYNJX7pFkyQ+VRu6uir7JoWPMd+e60MkBn55PQo3q8hJiKcLipyvMjpaKuKJhofVwbLOa/ds+Q4b3/P+L/spLza35zbaiQ98LJM6bC+RAVuHDrYI4GmiZhqUAA1S8uzgIpkX6DwsDjORmyFGxuiazYz8vwbFa0d1vSiemFyI0zGfiAAilbdtqr4jmF2zh9c9Y1xUH+sZjMa1ZLtJdsAK3dSgw3b6j4w3DdrDTKVDe/Hm8ltav/lM1jlXH3w=
  - secure: G5yp7673XRuFtscN03Iytj/AW4UgQMjOX8epfRgdvF/TiKETyNTzNxYevrZeMuKMJeyigZysANPQXK25IqmJWj/OdhqmjYf4EyKGPFcbbzw8Ln0JSpVqwF8zAlKI52SX33KZCatD0KP/4bVmXLW5VwmyYxSriG3/aX9eo4TgcB041Wt50+MiteFnYnMxmGvEckuybhcDobv2LpflEHyjwuLQrJ4CZsiAk54Z25uTsG1MeNliMC8mYs6uoyhKrZK5sG92qRpXRSs+/JvaKqY8LjB0QULm3opXXPZs9ImD13BOJUCjjZjwrZCp95MFJYbAjg3Qj+HY49yPogTq/IFm4UBkYtI5LTjBg5PSNDIlF26SrZcj798jueKNVetGd8vt6BXA02FiKKw3HsPVtldmG0DKJG70AqxnRnJNK/8gQfbXvnMZCm7WlODoM9VPTI9QEu/OjmE2uH9004CP2XzZ6WBvnHKLPYSTUD3JbmUfu0VOWoLoUQdPZU1+hsbdc976RPZZi3+3G93ZejrGaPdLiwksAi++nt91fRlvhCB7eXcbqxh91iwQLcg1unMXjJWVbQHGex9miIREdIhQ4AtfQrgxFsMp7UbopDytvbbGUl3rrlVNKjQIuttvkKYKOU5obhw2PMMt45JxYcGmNcfKI2kJN11INfwmq4w0tuwgUEU=
before_install:
- echo "TRAVIS_TAG = ${TRAVIS_TAG} - TRAVIS_BRANCH = ${TRAVIS_BRANCH}"
- echo "$HEROKU_AUTHTOKEN" | docker login --username=$HEROKU_USERNAME --password-stdin
  registry.heroku.com
- echo "$GITLAB_PWD" | docker login --username=$GITLAB_USERNAME= --password-stdin
  registry.gitlab.com
install:
- echo "skip install"
before_script:
- echo "skip before_script"
script:
- docker build -f Dockerfile -t $BUILD_TAG .
- docker tag $BUILD_TAG registry.heroku.com/$REPO/web
- docker tag $BUILD_TAG registry.gitlab.com/crixo/$REPO:$IMAGE_TAG
deploy:
  provider: script
  script: bash ./heroku-container-release.sh
  on:
    branch: master
