sudo: required
dist: trusty
language: node_js
node_js:
- '9.0'
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - export CI=false
  - export HEROKU_APP=woa-api-sample
  - export GITLAB_PRJ=woa-api
  - export IMAGE_TAG=latest
  - export TRAVIS_REPO=woa-api
  - export BUILD_TAG=$TRAVIS_REPO:$IMAGE_TAG
  - secure: p4yXFXVOtYdZ4RYneYwsGQsLqV8WS1N7UFzZh+cphNjDCQaOgXhlbXX6RtR5xdOd44aa1h6VuUehumoQ0t6exUp4a0yoepdHKyrJzIpfhulEw0a0CNCd1I2PkL82FaeUYZaP/UROk3AvKq8GSSxsWxtq6NbNyjhpW76DBvHnwr2XYCtLatsx9+mVDMrN3SyCtovZc6bf/wk8f4f1sNawc0qS9FOLME/tKmwRpK7R3MhKdTtfFC//QlfSHnwAq0deLqdrN1eXuhpnpquQ/B+lJ5fKKYF2ZFB6KqJdl4gIzKSVq1K6Z58NBFe5Kj6CeAfxvlrd6J4n9aBsQoSAlXH3yyln50M63b3tVRDVgs7pxDbOMab6fNETmK+RDJTKMd9HqORo1bGxUdksrJQ9d46/crQquYfWzu0HVpiPfQcG+s/QOCXSXZH4QvvgMsFOQ6SoO9yLf0k0PtmRuwaKNtqzHT9ZsOoUDdLtSpYMhRrGkCY4PFQFL9Z8ZbDl9OUZ5eiBO80fVi5NtEaaEDXGOkuTnLHquVJgoGAyEKcLOm1IMRk313sm2qdSBvz32hz1O9MsNMgneV4Tly1iri21ujUA2EftLp3aVF/Ge7o4K+pEj213HemV3RNCdw8s0auk7UHknpGS3cdcypaFmRGjvf7fhH4lOOppyr+YBvRr06F4k4w=
  - secure: rWyZMhxUQWF4Ynhkbku/FwoHkL4AJbXZ7ld3Y3Wo49tlXFKsWmlXCkVi40hlkTDOrKJ/tQdw0+L9KxH0tb6YkCsvKWl4twXqxNwhh5+UkcHbcg+v8mOZX771etHfL/7KS5RjzrH+ul7KxFf9LiScRlm+4u+JqJfzjzmTVjX1W65mgDngBhJMEHsappsRntha0Ep9snJXAzhsABjsT4xrOXz0dp7cB5BeqATSIf6rmfRctGx7FWWmF2qZ6dEpbMHhVVEeRiLniOrAOPib0IwAPlB4pkeuKub8VUVZkmeNveLcyx6mthP+9I6+OP1S+bAvfqz2L5tbZpHvirxM0PJBuGFbPDE+YVcTjBpjpIZ3lzsHrT9WUE6e5+1hLJqrmtrNxTd/sXqX1oU9CQXqrznROuKdbHnGRSjd+QXqiQt40FPGrcaFdozX8x23RR1zDRFVmHRTgnMNXQRkvr6Tvibu2aO5POCHmtXko1bZYfs/xndLAReol6PMN0KW5VTwDT2oraNfRXwAou1YZ4Hd9t3UXlMy9SPIwpSevEyMSYOajMm6/5f5mkx80ePOoCtkjmYbSY9zIXD1ykltwVaND4wSJvw/y2kGeWZAJ+ngoB/JETP3W6y6dwXkPR01GJ30lYA2gew8GxPhqVjglkeTLjRXQ/ppUENVbPIA81+uepO2cPo=
  - secure: QUFb4NHQiHewG1YjY+Ibxi0VcSPEDIrNnZc3xe/Sg4npmbDJdG4pvjOwvtvQ7zASZuZPMgwFsm39K4rBi8u24ot7DEEElGqjC6YApeiX5wUlh15Ll6Et2JDFKrEr2ku5NQ3056ft2HnGj/or0SsqBfgEJgJurcByCe/nVc4gMO7E5ARdbCCFRdysGMyYpEF/93BgMj6/B4TaDzCkQVBbj8FusJ8e3qCyg/JTet29I7YwnQyY5NtVtVPOcWC7xvLDxIALrhbApbKjNwy3Ux2/oDJMcQSu1BNfnosBNzBfGiolxyfJwm9Cnr7zDPIPtWHGtlLh24GKegxKA4qMMvN60bndTIDsP/lq1c7SZSzL1k8i0wahfI/3XNu0H/17FJ6e5kGg+GSzhlAlQXDFXT8EU1fks7KWeZHFUdkHADu8RTbR8GIPT6fUCn2Vg41eEiebFzac+1XVHZxk5r+dERYA7WQoI3tILe7shUgX6+2AKydVqlnNjjtQADOPzU9SgHICeCLIw6zskPBDp/4/ZTKCEuGSNhp3jv0tVHN45W7UdBgq5z9GTdHjXvBEKPhyzwtd+aKAd+FMJ9tvuI8Ik7ZoRT8sUIjslW97Dtxy+ueoqZ0NdUj9fpdvVKkdW9gZr68GU+GI4k1mwua5P9v6+urlkKEhYNe6UzNTPBP3eva3uts=
  - secure: CSehIptCCZDPFxP4wnSs2kFN7Mt/wvIsSzytVYYixbztXCutugetjUfsoxd24RxSsRP54FoyVZbLSmT4KV+DxV5JBKP5Ngci8ZE+r7w7cBiuTMt4ZJkI6RAhzR1AouXWJAgRk5nBwwbfXOdyt4H4kVyUX87VbAGB9RgfkU+v5vUlqlezM8ehbIMFiyftKLVlMqFpiRDRPG1nDQI0pr1O2c1Ya4hkBmk/xEmyz3Zuz+1M5AGvds6OLxyutzC7hHbDWxipJQ7/o333XRnaBMjV49Ie07EnEER2MpShoWmUXRbctj+RUjPi2NoIN8TvizNvFq9iXCWK5C90483+BbzSGN0ggI9XnYNRcOluSAY3i+QkhS6mnJI0+jdIw41MocHxBgQ1+FYQRK8jiY+RB1dgMT8mzIB2Sy4uoIFfPhKqhQQcVCSQy6sdh7yNuM63s7zVyp5tSFtQUn6hpBkfBM/LgJxdI5Uzq4IqBmr980VoRovunFSqXGWRG79IH1x7RSciYZUJ4g+6zbJg5EQF3sAOoSFIYBr7qttD6PWx5dbJJwT6GJ3sN4ApFEiYjDIe8WQK/yl2Cf2MXDVigWeOLhZ4lYpXwKd33ZcbhtyWb3zNMWHqelW5821ezFoyumMGq2ZecekpBTL7vIBmTjWitstorPOmtVzpvyE32FGak5WSCnI=
before_install:
- echo "TRAVIS_TAG = ${TRAVIS_TAG} - TRAVIS_BRANCH = ${TRAVIS_BRANCH} - BUILD_TAG = ${BUILD_TAG}"
- echo "$HEROKU_AUTHTOKEN" | docker login --username=$HEROKU_USERNAME --password-stdin
  registry.heroku.com
- echo "$GITLAB_PWD" | docker login --username=$GITLAB_USERNAME --password-stdin
  registry.gitlab.com
install:
- echo "skip install"
before_script:
- echo "skip before_script"
script:
- docker build -f Dockerfile -t $BUILD_TAG .
- docker tag $BUILD_TAG registry.heroku.com/$HEROKU_APP/web
- docker tag $BUILD_TAG registry.gitlab.com/crixo/$GITLAB_PRJ:$IMAGE_TAG
deploy:
  provider: script
  script: bash ./heroku-container-release.sh
  on:
    branch: master
